#!/bin/bash
set -e
npm ci
./minify
npm run test
mvn clean install
docker buildx build --platform linux/s390x,linux/amd64,linux/ppc64le,linux/arm64/v8,linux/arm/v7 \
  -t housewrecker/gaps:alpha \
  -f Dockerfile --push .