#!/bin/bash

##
# Copyright 2019 Jason H House
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

set -e
VERSION=0.9.12
JAR_VERSION="GapsWeb/target/GapsWeb-$VERSION.jar"
ZIP_VERSION="GapsAsJar-$VERSION.zip"
npm ci
./minify
npm run test
mvn clean install

docker buildx build --platform linux/s390x,linux/amd64,linux/ppc64le,linux/arm64/v8,linux/arm/v7 \
  -t housewrecker/gaps:latest \
  -f Dockerfile --push .
docker buildx build --platform linux/riscv64 -t housewrecker/gaps:risc-latest -f Dockerfile.riscv64 --push .

docker buildx build --platform linux/s390x -t housewrecker/gaps:s390x-v$VERSION -f Dockerfile --push .
docker buildx build --platform linux/amd64 -t housewrecker/gaps:x64-v$VERSION -f Dockerfile --push .
docker buildx build --platform linux/ppc64le -t housewrecker/gaps:ppc64le-v$VERSION -f Dockerfile --push .
docker buildx build --platform linux/arm64/v8 -t housewrecker/gaps:arm-v$VERSION -f Dockerfile --push .
docker buildx build --platform linux/arm/v7 -t housewrecker/gaps:arm32v7-v$VERSION -f Dockerfile --push .
docker buildx build --platform linux/riscv64 -t housewrecker/gaps:risc-v$VERSION -f Dockerfile.riscv64 --push .

## Making Windows/Linux/Mac Zip
mkdir -p GapsOnJar
rm -f GapsAsJar/*.jar
rm -f GapsAsJar/*.md
rm -f GapsAsJar/*.sh
rm -f GapsAsJar/*.bat
cp $JAR_VERSION GapsAsJar/gaps.jar
cp README.md GapsAsJar/
cp startOnWindows.bat GapsAsJar/
cp startOnLinuxAndMac.sh GapsAsJar/
zip -r $ZIP_VERSION GapsAsJar/