#!/bin/bash
VERSION=0.8.0
JAR_VERSION="GapsWeb/target/GapsWeb-$VERSION.jar"
ZIP_VERSION="GapsAsJar-$VERSION.zip"
./minify
mvn clean install deploy
docker buildx build --platform linux/ppc64le,linux/s390x,linux/amd64 -t housewrecker/gaps:latest -f Dockerfile --push .
docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t housewrecker/gaps:arm-latest -f Dockerfile.arm64 --push .
mkdir -p GapsOnWindows
rm $ZIP_VERSION
rm GapsAsJar*.jar
rm GapsAsJar/README.md
cp $JAR_VERSION GapsAsJar/gaps.jar
cp README.md GapsAsJar/
zip -r $ZIP_VERSION GapsAsJar/