#!/bin/bash
set -e
npm ci
./minify
mvn clean install
docker buildx build --platform linux/s390x,linux/amd64 -t housewrecker/gaps:alpha -f Dockerfile --push .
docker buildx build --platform linux/riscv64 -t housewrecker/gaps:risc-alpha -f Dockerfile.riscv64 --push .
docker buildx build --platform linux/ppc64le -t housewrecker/gaps:ppc64le-alpha -f Dockerfile.ppc64le --push .
docker buildx build --platform linux/arm64 -t housewrecker/gaps:arm-alpha -f Dockerfile.arm64 --push .
docker buildx build --platform linux/arm/v7 -t housewrecker/gaps:raspbian-alpha -f Dockerfile.raspbian --push .