#For Testing Only

FROM openjdk:11.0.6-jre-slim

MAINTAINER jh5975@gmail.com

EXPOSE 32400

RUN mkdir -p /usr/data

COPY movieIds.json /usr/data

RUN mkdir -p /usr/app

WORKDIR /usr/app

COPY GapsWeb/target/GapsWeb-0.4.0-SNAPSHOT.jar /usr/app/

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=no-ssl-no-login", "GapsWeb-0.4.0-SNAPSHOT.jar"]