#!/bin/bash
npm run minify-input-css
npm run uglifyjs-index-js
npm run uglifyjs-configuration-js
npm run uglifyjs-libraries-js
npm run uglifyjs-recommended-js
npm run uglifyjs-common-js
npm run uglifyjs-payload-js
npm run uglifyjs-mislabeled-js
npm run uglifyjs-collections-js
npm run uglifyjs-collections-actors-js
npm run uglifyjs-collections-directors-js