pipeline {
    environment {
        registry = "housewrecker/gaps"
        registryCredential = 'dockerhub'
    }

    agent {
        docker {
            image 'adoptopenjdk/maven-openjdk8'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Java Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Junit Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'GapsWeb/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Building image') {
            steps{
                script {
                    docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
}
    }
}