pipeline {
    agent none
    stages {
        stage('Java Build') {
            agent {
                docker {
                    image 'adoptopenjdk/maven-openjdk8'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'GapsWeb/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Building image') {
            environment {
                registry = "housewrecker/gaps"
                registryCredential = 'dockerhub'
            }
            agent {
                dockerfile {
                    filename "Dockerfile.ssl"
                    args '-i  -p 2222:8484 -v /gaps:/usr/data --name gaps_dev gaps_dev'
                }
            }
            steps{
                script {
                    docker.build registry + ":v0.2.3.$BUILD_NUMBER"
                }
            }
        }
    }
}