pipeline {
    agent none
    stages {
        stage('Java Build') {
            agent {
                docker {
                    image 'adoptopenjdk/maven-openjdk8'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
                sh 'mvn test'
                sh 'docker build -f Dockerfile.ssl -t housewrecker/gaps:v0.2.3.$BUILD_NUMBER .'
            }
            post {
                always {
                    junit 'GapsWeb/target/surefire-reports/*.xml'
                }
            }
        }
    }
}